print ("WELCOME TO AREA  FINDING . COM")
print ("HERE U CAN FIND THE AREA OF ANY FEILD")
LENGHT = 1
BREATH = 1
LENGHT = input ("ENTER THE LENGHT OF YOUR ROOM\n")
BREATH = input ("ENTER THE BREATH OF YOUR ROOM\n")
RESULT = int(LENGHT)*int(BREATH)
print (RESULT)      

     

 
