print ("WELCOME TO BIODATA COLLECTION.COM")
name = str(input("ENTER YOUR FIRST NAME: \n"))
sirname = str(input("ENTER YOUR SIR NAME: \n"))
age = int(input("ENTER YOUR AGE: \n"))
height = int(input("ENTER YOUR HEIGHT IN inch: \n"))
print (f"HELLO {name}")
print (f"Your Name Is {name} {sirname}")
print (f"Your Age is {age}")
print (f"Your height Is {height} inchs")
print ("NOW IT IS THE TIME TO EVALLUVATE THE DATA ABOUT YOU GOT FROM YOU")
print (f"{name}, A Wonderful Name")
if age > 18:
    print (f"{age},You are a Youth")
else:
    print (f"{age},You are a Kid") 
print (f"{height}/39.37 this your height in metres" )       
print ("TYPE THIS FORMULA AND PRESS ENTER")
print ("to get your height in metres")