COSTOFMEAL=1
TAXOFMEAL = 1
TIPOFMEAL = 1
COSTOFMEAL = input("TELL THE COST OF MEAL\n")
TAXOFMEAL = input("TELL THE TAX OF MEAL \n")
TIPOFMEAL  = input("TELL THE TIP OF MEAL\n")
RESULT = int(COSTOFMEAL)+int(TAXOFMEAL)+int(TIPOFMEAL)
print (f"YOUR COST OF MEAL IS {COSTOFMEAL}")
print (f"YOUR TAX OF MEAL IS {TAXOFMEAL}")
print (f"YOUR TIP OF MEAL IS {TIPOFMEAL}")
print (f"THE TOTAL IS {RESULT}")
