print ("WELCOME TO SONGLIRECAL.COM")
print ("HERE YOU ARE GOING TO FIND ANY KIND OF OR ANY LANGUAGE SONG WITH IT'S LYRICS ")
print ("THIS SECTOIN IS FOR THE MOVIE (DIL BECHARA)")
input ("WHICH LYRICS DO YOU WANT?")
LYRICS=str(input() ) 
if LYRICS==("THEME SONG"):
        print (" HERE IS DIL BECHARA'S THEME SONG=")
        print ("Dil Bechara\nFriend Zone Ka Maara")
        print ("Dil Bechara")
        print ("Friend Zone Ka Maara")
        print ("Friend Zone Ka Maara")
        print ("Koyi Toh Bata De Kya Karoon")
        print ("Koyi Bata De Kya Karoon")
        print ("Dil Bechara")
        print ("Friend Zone Ka Maara")
        print(" L Mein Joda OVE")
        print ("Maine Toh Love Love Love Hi Kiya")
        print ("Usne Joda IKE")
        print ("Mere Ko Like Like Like Hi Kiya")
        print ("Dil Bechara")
        print ("Friend Zone Ka Maara")
        print ("Oh Baby Yaad Hai Mujhe")
        print ("Tera Birthday Day Day")
        print ("Tera Birthday Day Day Day")
        print ("Tu Har Saal Mera Birthday")
        print ("Bhool Bhool Bhool Jaye")
        print ("Roz Tere Call Ki Main Raah Dekhun")
        print ("Tu SMS Bhi Na Kare")
        print ("Tu Mujhe Miss Bhi Na Kare")
        print ("Kyun Mujhe Miss Bhi Na Kare")
        print ("Kyun?")
        print ("Dil Bechara")
        print ("Friend Zone Ka Maara")
        print ("Dil Bechara")
        print ("Friend Zone Ka Maara")
        print ("Friend Zone Ka Maara")
elif LYRICS==("TARE GIN"):
        print("HERE IS TARE GIN")
        print("Jabse hua hai yeh achcha sa lagta hai")
        print("Dil ho gaya phir se bachcha sa lagta hai")
        print("Ishq ragon mein jo behta rahe jaake")
        print("Kaanon mein chup ke se kehta rahe")
        print("Taare ginn, taare ginn")
        print("Soye bin saare gin")
        print("Ek haseen maza hai yeh")
        print("Maza hai ya saza hai yeh")
        print("Jabse hua hai yeh achcha sa lagta hai")
        print("Dil ho gaya phir se bachcha sa lagta hai")
        print("Ishq ragon mein jo behta rahe jaake")
        print("Kaanon mein chup ke se kehta rahe")
        print("Taare ginn, taare ginn")
        print("Soye bin saare gin")
        print("Ek haseen maza hai yeh")
        print("Maza hai ya saza hai yeh")
        print("Roko ise jitna")
        print("Mehsoos ho yeh utna")
        print("Dard zara sa hai")
        print("Thoda dawa sa hai")
        print("Ismein hai jo taira")
        print("Wahi to dooba hai")
        print("Dhokha zara sa hai")
        print("Thoda wafa sa hai")
        print("Yeh vaada hai ya iraada hai")
        print("Kabhi yeh zyada hai")
        print("Kabhi yeh aadha hai")
        print("Taare ginn taare ginn")
        print("Soye bin saare gin")
        print("Ek haseen maza hai yeh")
        print("Maza hai ya saza hai yeh")
elif LYRICS==("MASKHARI"):
      print ("HERE IS MASKHARI")
      print ("Kar band sabhi ghadiyan")
      print ("Aur mood bana badhiyan")
      print ("Mukhde pe jala le tu")
      print ("Muskaan ki phuljhadiyan")
      print ("Karle maskhari, thodi maskhari")
      print ("Achcha khasa kaam maskhari")
      print ("Phokat mein badnaam maskhari")
      print ("Dil ko de aaram maskhari")
      print ("Peeda haari balm maskhari")
      print ("Halki fulki si maskhari")
      print ("Thandi kulfi si maskhari")
      print ("Ho maskhari")
      print ("Ho maskhari")
      print ("Ho maskhari maskhari")
      print ("Jeene ki wajah maskhari")
      print ("Thodi be-wajah maskhari")
      print ("Karke to dekh maskhari")
      print ("Deti hai maza maskhari")
      print ("Thodi si naram maskhari")
      print ("Thodi si garam maskhari")
      print ("Thodi si haya maskhari")
      print ("Thodi besharam maskhari")
      print ("Dariya se pakad machhli")
      print ("Baadal se chhuda bijli")
      print ("Dil mein jo bhari tere")
      print ("Har aaj mita khujli")
      print ("Karle maskhari, thodi maskhari")
      print ("Achcha khasa kaam maskhari")
      print ("Phokat mein badnaam maskhari")
      print ("Dil ko de aaram maskhari")
      print ("Peeda haari balm maskhari")
      print ("Achcha khasa kaam maskhari")
      print ("Phokat mein badnaam maskhari")
      print ("Dil ko de aaram maskhari")
      print ("Peeda hari baam maskhari")
elif LYRICS==("KHULKE JINE KA TARIKA TUMHE BATATE HAI"):
      print ("HERE IS KHULKE JINA KA TARIKA TUMHE BATATE HAI")
      print("Khulke Jeene Ka")
      print("Tareeka Tumhein Sikhate Hain")
      print("Hanske Dekho Na")
      print("Lateefa Tumhein Sunate Hain")
      print("Umar Ke Saal Kitne Hai Gin Gin ke Kya Karna")
      print("Beet Jaye Na Ginti Mein Hi Varna")
      print("Aao Film’on Ke Beadab Gaane Gaate Hain")
      print("Heroine Hero Aaj Hum Tum Ban Jate Hain")
      print("Khul Ke Jeene Ka")
      print("Tareeka Tumhein Sikhate Hain")
      print("Hanske Dekho Na")
      print("Lateefa Tumhein Sunate Hain")
      print("Khushiyan Toh Rakhi Hain Pocket Mein")
      print("Kagaz Ke Nanhe Se Packet Mein")
      print("Inki Bijli Ki Tarah Kyun Bachat Kare Batao Na")
      print("Kharch Kar Dalenge Saari Aaj Hi Aao Na")
      print("Hai Mehnge Dard Bade")
      print("Aur Muskaan Payi Humne Maut Mein")
      print("Khulke Jeene Ka")
      print("Tareeka Tumhein Sikhate Hain")
      print("Hanske Dekho Na")
      print("Lateefa Tumhein Sunate Hain")
      print("Umar Ke Sal Kitne Hai Gin Gin Ke Kya Karna")
      print("Beet Jaye Na Ginti Mein Hi Varna")
      print("Aao Film’on Ke Beadab Gaane Gaate Hain")
      print("Heroine Hero Aaj Hum Tum Ban Jate Hain")
      print("Dil Ki Hai Itni Hi Nadaani")
      print("Chutki Mein Ho Jaye Romaani")
      print("Yaari Aur Chahat Ke Jo Bich Maheen Sarhad Hai")
      print("Paar Usko Kar Jana Dil Ki Buri Aadat Hai")
      print("Aasani Se Aa Jaye")
      print("Do Anjaan Ankhiyon Ki Giraft Mein")
      print("Khulke Jeene Ka")
      print("Tareeka Tumhein Sikhate Hain")
      print("Hanske Dekho Na")
      print("Lateefa Tumhein Sunate Hain")
      print("Umar Ke Saal Kitne Hai Gin Gin Ke Kya Karna")
      print("Beet Jaye Na Ginti Mein Hi Varna")
      print("Aao Film’on Ke Beadab Gaane Gaate Hain")
      print("Heroine Hero Aaj Hum Tum Ban Jaate Hain")
      print("Khul Ke Jeene Ka")
      print("Tareeka Tumhein Sikhate Hain")
      print("Hanske Dekho Na")
      print("Lateefa Tumhein Sunate Hain")
elif LYRICS==("MERA NAME HAI KIZIE KIZIE"):
    print ("HERE IS MERA NAME KIZIE KIZIE")
    print ("Mera Naam Kizie, Kizie, Kizie")
    print("Thodi Si Mushkil Thodi Easy")
    print("Mera Naam Manny, Manny, Manny")
    print("Chahat Mein Lipti Si Bechaini")
    print("Main Din Hoon Toh Tu Raat Hai")
    print("Is Jodi Ki Kya Baat Hai")
    print("Total Azooba Hai")
    print("Mera Naam Kizzie, Kizzie, Kizzie")
    print("Thodi Si Mushkil Thodi Easy")
    print("Mera Naam Manny, Manny, Manny")
    print("Chahat Mein Lipti Si Bechaini")
    print("Main Din Hoon Toh Tu Raat Hai")
    print("Is Jodi Ki Kya Baat Hai")
    print("Total Azooba Hai")
    print("Galon Pe Dono Ke Dayein Bayein Dimple")
    print("Hai Complicated Par Dikhne Mein Simple")
    print("Google Pe Dhundhon Ya Saari Duniya Chhano")
    print("Apne Jaisa Na Milega Koyi Sample")
    print("Galo Pe Dono Ke Dayein Bayein Dimple")
    print("Hai Complicated Par Dikhne Mein Simple")
    print("Google Pe Dhundhon Ya Saari Duniya Chhano")
    print("Apne Jaisa Na Milega Sample")
    print("Mera Naam Kizzie, Kizzie, Kizzie")
    print("(Yes It’s Easy)")
    print("Thodi Si Mushkil Thodi Easy")
    print("Mera Naam Manny, Manny, Manny")
    print("Chahat Mein Lipti Si Bechaini")
    print("Main Din Hoon Toh Tu Raat Hai")
    print("Is Jodi Ki Kya Baat Hai")
    print("Total Azooba Hai")
elif LYRICS==("MAI TUMHARA"):
        print("HERE IS MAI TUMHARA")
        print("Tum na huey mere toh kya")
        print("Hmm.. Tum na huey mere toh kya")
        print("Main tumhara, main tumhara, main tumhara raha")
        print("Mere chanda main tumhara sitaara raha")
        print("Rishta raha bas rait ka")
        print("Aye samandar main tumhara kinaara raha")
        print("Main tumhara, main tumhara, tumhara raha")
        print("Tum na huey mere toh kya")
        print("Tu hi pehli guzarish, hasrat bhi tu aakhiri") 
        print("Maahi mere naseeh marzi bata kya teri")
        print("Main tumhara, main tumhara, main tumhara raha")
        print("Mere chanda main tumhara sitaara raha")
        print("Main jaadon ke mahine ki tarah")
        print("Aur tum ho Pashmine ki tarah")
        print("Main deewaron ki tarah hoon")
        print("Tum jaise ho dareecha")
        print("Main bageecha jo tumne seencha")


