print("Hi This Is the Answer Key to Prject4")
print("Value 1 i 2")
print("Value 2 is 8")
input("Type in `result` to see all performed Calculation with number\n")
print("+=",8+2)
print("-=",8-2)
print("*=",8*2)
print("/=",8/2)
print("//=",8//2)
print("%=",8 % 2)
print("**=",8**2)
