print("Hey There\nHello guys This The Solution Set Of The Second Project That I Gave to Creat A Quiz Or A Registration Form")
print("So Let's Start Our Form\nHello Welcome To quiz.com Thank You For Choosing Our Website For Testing You'knowledge") 
print("Hm....Hope You Are Ready")
input("Please Enter You'r Name\n")
input("Please Enter You'r Email\n")
input("Here's The First Question:\n2+4*5-30\n")
input("Second Question:\n6+4*10\n")
input("Third Question:\nTell The Name Of Our Prime Minister\n")
print("SO,You Sucess quaifies Into The Next Round Of The Quiz",end = "Till Then Bye")
