# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_My_Window(object):
    def setupUi(self, My_Window):
        My_Window.setObjectName("My_Window")
        My_Window.resize(801, 600)
        font = QtGui.QFont()
        font.setPointSize(18)
        My_Window.setFont(font)
        self.centralwidget = QtWidgets.QWidget(My_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.btn = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.press_it())
        self.btn.setGeometry(QtCore.QRect(600, 490, 161, 41))
        self.btn.setObjectName("btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 221, 111))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        My_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(My_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 33))
        self.menubar.setObjectName("menubar")
        My_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(My_Window)
        self.statusbar.setObjectName("statusbar")
        My_Window.setStatusBar(self.statusbar)

        self.retranslateUi(My_Window)
        QtCore.QMetaObject.connectSlotsByName(My_Window)

    def press_it(self):
        self.hello_world_label.setText("Boom!")
           
    def retranslateUi(self, My_Window):
        _translate = QtCore.QCoreApplication.translate
        My_Window.setWindowTitle(_translate("My_Window", "My_Window"))
        self.btn.setText(_translate("My_Window", "Click Me!"))
        self.label.setText(_translate("My_Window", "Hi! Vivaan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    My_Window = QtWidgets.QMainWindow()
    ui = Ui_My_Window()
    ui.setupUi(My_Window)
    My_Window.show()
    sys.exit(app.exec_())
